import assert from 'node:assert/strict'
import { nextWindow, prefetchDecision } from '../patches/reading-session.js'
let w = nextWindow(null, 'all:1', 24, 24)
assert.equal(prefetchDecision(w, 5, 1800, 800), null)
assert.deepEqual(prefetchDecision(w, 6, 1800, 800), {reason:'quarter',target:6})
w = nextWindow(w, 'all:1', 48, 48)
assert.equal(prefetchDecision(w, 6, 4800, 800), null, 'append cannot recursively fetch entire library')
assert.equal(prefetchDecision(w, 29, 1900, 800), null)
assert.equal(prefetchDecision(w, 30, 1800, 800).target, 30)
w = nextWindow(w, 'all:1', 72, 72)
assert.equal(prefetchDecision(w, 30, 4800, 800), null)
assert.equal(prefetchDecision(w, 54, 1800, 800).reason, 'quarter')
assert.equal(prefetchDecision(w, 50, 80, 800).reason, 'near-end')
assert.equal(prefetchDecision(w, -1, 80, 800).reason, 'near-end', 'tail can prefetch while virtual rows are temporarily absent')
assert.equal(prefetchDecision(w, -1, 1800, 800), null, 'missing rows alone must not fetch more pages')
w = nextWindow(w, 'category:2', 20, 20)
assert.equal(w.start,0);assert.equal(w.size,20)
assert.equal(prefetchDecision(w, 4, 1800, 800), null)
assert.equal(prefetchDecision(w, 5, 1800, 800).target,5)
w = nextWindow(w, 'category:2', 20, 40)
assert.equal(prefetchDecision(w, 18, 0, 800),null,'duplicate-only pages stop speculative chaining; manual remains available')
w = nextWindow(w, 'category:2', 35, 60)
assert.equal(w.stalled,false);assert.equal(w.start,20)
assert.equal(prefetchDecision(w, 23, 500, 800).reason,'quarter')
assert.equal(prefetchDecision(nextWindow(null,'empty',0,0),0,0,800),null)
console.log('PASS per-batch threshold, one-page-ahead bound, short list, reset, duplicates, empty')
