[Unit]
Wants=ai-news-proxy.service
After=ai-news-proxy.service
[Service]
Environment="PROXY_URI=http://127.0.0.1:17890"
Environment="PROXY_URL_REGEX=^https?://(?!(?:127[.]0[.]0[.]1|localhost)(?::|/))"
